[2014-03-05 04:23:53] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 04:26:51] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 04:35:16] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 04:37:41] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 04:37:53] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 04:38:26] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'C:\xampp\htdocs...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #4 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2014-03-05 04:38:35] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'C:\xampp\htdocs...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #4 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2014-03-05 04:38:39] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'C:\xampp\htdocs...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #4 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2014-03-05 04:39:39] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 04:39:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 04:44:34] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 04:45:04] log.ERROR: exception 'ErrorException' with message 'Undefined offset: 1' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:974 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(974): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'C:\xampp\htdocs...', 974, Array) #1 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #4 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #5 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #6 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #7 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #8 {main} [] []
[2014-03-05 04:45:16] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 04:45:37] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 04:55:51] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 06:08:54] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 06:09:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 06:17:20] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 06:17:49] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290 Stack trace: #0 [internal function]: Illuminate\Routing\Controllers\Controller->missingMethod(Array) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('missingMethod', Array) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'missingMethod', Array) #4 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Array) #5 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #6 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #7 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #8 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #11 {main} [] []
[2014-03-05 06:31:26] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2014-03-05 09:41:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\laravel-authentication\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\laravel-authentication\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
